name: processData

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - run: |
        cd node/
        npm install
    - name: fetchData
      run: |
        npm run fetchData
      working-directory: ./node
    - name: calculateData
      run: |
        npm run calculateData
      working-directory: ./node
    - name: transferData
      run: |
        npm run transferData
      working-directory: ./node
    - name: add new files
      run: |
        git status
        git add .
        git commit -m "data files changed"
        git push
      working-directory: ./